export const signupUser = async(req,res) => {
    try{

    }catch(error){
        console.log(error)
    }
}